// ── Phase 5 — Output export (Markdown report) ──────────────────────────────
// A minimal, dependency-free "output display" layer: renders the aggregated
// review as a portable Markdown document that can be copied or downloaded —
// the browser-app equivalent of piping a CLI table or Streamlit report out.

function generateMarkdownReport(meta, parsed, results, aggregate) {
  const lines = [];
  const stamp = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';

  lines.push(`# Repo Review — ${meta.full_name}`);
  lines.push('');
  lines.push(`**Overall score:** ${aggregate.overall}/10 (Grade ${aggregate.grade})  `);
  lines.push(`**Branch:** ${parsed.branch}  |  **Generated:** ${stamp}`);
  if (aggregate.failed.length) {
    lines.push('');
    lines.push(`> ⚠ ${aggregate.failed.length}/${AGENT_ORDER.length} agent(s) failed: ${aggregate.failed.map(n => AGENT_META[n]?.label || n).join(', ')}. Score reflects the remaining agents only.`);
  }
  lines.push('');

  lines.push('## Executive summary');
  lines.push(aggregate.executiveSummary);
  lines.push('');

  const topIssues = aggregate.prioritizedIssues.filter(i => i.severity === 'high' || i.severity === 'medium').slice(0, 5);
  if (topIssues.length) {
    lines.push('## Top priorities');
    topIssues.forEach((p, i) => {
      const m = AGENT_META[p.agent];
      lines.push(`${i + 1}. **[${(p.severity || '').toUpperCase()}]** ${p.title} _(${m ? m.label : p.agent})_`);
    });
    lines.push('');
  }

  lines.push('## Scores by dimension');
  lines.push('| Dimension | Score |');
  lines.push('|---|---|');
  AGENT_ORDER.forEach(name => {
    const r = results[name] || {};
    const m = AGENT_META[name];
    lines.push(`| ${m.emoji} ${m.label} | ${r.score ?? '?'}/10 |`);
  });
  lines.push('');

  AGENT_ORDER.forEach(name => {
    const r = results[name] || {};
    const m = AGENT_META[name];
    lines.push(`## ${m.emoji} ${m.label} — ${r.score ?? '?'}/10`);

    if (r.error) {
      lines.push(`_Agent failed: ${r.error}_`);
      lines.push('');
      return;
    }

    if (r.summary) { lines.push(r.summary); lines.push(''); }

    if ((r.strengths || []).length) {
      lines.push('**Strengths:**');
      r.strengths.forEach(s => lines.push(`- ${s}`));
      lines.push('');
    }
    if ((r.issues || []).length) {
      lines.push('**Issues:**');
      r.issues.forEach(i => {
        const file = i.file ? ` (\`${i.file}\`)` : '';
        lines.push(`- [${(i.severity || '').toUpperCase()}] ${i.title}${file}${i.detail ? ` — ${i.detail}` : ''}`);
      });
      lines.push('');
    }
    if ((r.suggestions || []).length) {
      lines.push('**Suggestions:**');
      r.suggestions.forEach(s => lines.push(`- ${s}`));
      lines.push('');
    }
  });

  lines.push('---');
  lines.push('_Generated by Repo Reviewer_');
  return lines.join('\n');
}

function flashButton(btn, tempLabel) {
  const orig = btn.textContent;
  btn.textContent = tempLabel;
  btn.disabled = true;
  setTimeout(() => { btn.textContent = orig; btn.disabled = false; }, 1500);
}

async function copyReport() {
  if (!window._lastResults || !window._lastAggregate) { showError('Run the agents first.'); return; }
  const md  = generateMarkdownReport(window._repoMeta, window._repoParsed, window._lastResults, window._lastAggregate);
  const btn = document.getElementById('copy-report-btn');
  try {
    await navigator.clipboard.writeText(md);
    flashButton(btn, 'Copied ✓');
  } catch (e) {
    showError('Could not copy to clipboard — your browser may be blocking clipboard access.');
  }
}

function downloadReport() {
  if (!window._lastResults || !window._lastAggregate) { showError('Run the agents first.'); return; }
  const md   = generateMarkdownReport(window._repoMeta, window._repoParsed, window._lastResults, window._lastAggregate);
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `${(window._repoMeta.name || 'repo')}-review.md`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
  flashButton(document.getElementById('download-report-btn'), 'Downloaded ✓');
}
